# configs/dev.yaml
project:
  name: log-guardian
  env: development

paths:
  data_raw: data/raw
  data_processed: data/processed
  data_samples: data/samples
  models_artifacts: models/artifacts/dev
  models_registry: models/registry.json
  logs: logs/dev.log

ingestion:
  batch_size: 200
  file_type: json
  timestamp_field: timestamp

features:
  window_size_minutes: 2
  aggregation_methods: [mean, max]
  categorical_encoding: onehot

modeling:
  algorithm: isolation_forest
  params:
    n_estimators: 50   # faster training in dev
    contamination: auto
    random_state: 42
  train_split: 0.7
  save_model: true

api:
  host: 127.0.0.1
  port: 8000
  reload: true   # enable hot-reload for development

logging:
  level: DEBUG
  format: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"
  log_file: logs/dev.log
  max_size: 5000000  # 5 MB for development